### ISSUE TITLE
Alternative implementation

### ISSUE THREAD

**Issue by arximboldi** [za-creature/double-latte#1]
Hi man!

It seems that we had the same idea :)
Here is my implementation: https://github.com/arximboldi/heterarchy

Have a good day!

**Comment by za-creature** [comment]
Hey,

I actually used your old implementation as a reference ( http://sinusoid.es/mixco/mixco/multi.html ). Nice to see it decoupled and posted on github and npm; I'll update my readme to link to your new project as an alternative!

**Comment by za-creature** [comment]
Done.

You should consider removing the `coffee-script` dependency as it will install a local (and unused) version of `coffee` in the `node_modules/heterarchy` folder. Since the module must be imported and may only be used with Coffeescript classes, the parent folder must already have a working coffeescript compiler,

If you wish to compile to js, you can add `coffee-script` as a dev dependency and use a `npm prepublish` script to compile your coffee code into javascript prior to publishing. [Here's an example](https://github.com/planetary/kepler-node-api/blob/master/package.json#L42)

**Comment by ghost** [comment]
Thanks for the tip, I am not really a web developer so some of thes NPM details escape my understanding :-)

And thanks for giving credit in the README! When I was reading your implementation I thought that we were bastard siblings or something, now I understand everything hehe.

One quick remark though: the original code was in GPLv3 and you relicensed your derived implementation as MIT, which technically is a violation of the GPL [1]. It's no big deal, and actually `heterarchy` is also MIT now, but other time just send an email to ask permission because you can get in trouble if you do this with the wrong person :smile: 

Cheers!

[1] To be clear: it is a violation to re-license GPL code as MIT, but it is ok to "use" GPL library in a MIT project.

**Comment by za-creature** [comment]
I said _a_ reference, not _the only_ reference. Sorry for not being more clear about the whole process: I did not include any of your code [1]. While I did read it and compared your implementation to mine, I wrote everything from scratch, using the idea from [this gist](https://gist.github.com/darrrk/75d6a6a4d431e7182888). In fact, I only found out about mixco halfway through and even so, I would not have used it due to the following:
- GPL is incompatible with what I'm trying to achieve; LGPL may have worked for me, but:
- I want to use it for browser components, and don't want or need the overhead of underscore

Since you've re-released everything as MIT, we're on the same page here and I don't want to start a whole thing about this. I just wanted to clear the air because as a Romanian citizen, I'm a bit sensitive about [plagiarism accusations](http://en.wikipedia.org/wiki/Victor_Ponta#Plagiarism_controversy)

[1] okay, I may have borrowed some bits of test code, but those are not technically part of the library, they are not significant enough for the entire project to be considered derivative work, and I believe the test cases themselves were described in the Dylan paper anyway.

**Comment by ghost** [comment]
Sorry, I didn't mean that you plagiarized it, and I think that the usage you did of the code was fair. I just meant that there is a blurry line about what _derived work_ means in the context of the GPL and it's better to be safe and ask the people involved even if you are just using the code, even if just as reference [1]. As I said, everything is fine with me though and I don't have any problem with it. I think that you did a nice work and there are some merits to your implementation.

[1] I know that some people from companies like Apple or Microsoft refuse to even _read_ GPL code because of this reason.

**Comment by za-creature** [comment]
Wow, I did not know it was that bad. Okay, thanks for the tip, will keep it in mind.

Happy coding!
